---

- hosts: manager
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: no

  tasks:
  - name: Tag and push to local registry
    docker_image:
      # Image will be nginx_moo
      name: nginx_moo
      # Will be pushed to localhost:5000/nginx_moo
      repository: localhost:5000/nginx_moo
      push: yes
      source: local