---

# - hosts: all
#   remote_user: vagrant
#   become: yes
#   become_method: sudo
#   gather_facts: no

#   tasks:
#   - name: Update docker config
#     copy:
#       src: ./config_files/daemon.json
#       dest: /etc/docker/daemon.json
#       mode: '0644'
#       notify: restart docker

#   handlers:
#   - name: restart docker
#     register: conf_nginx
#     service:
#       name: docker
#       state: restarted
#   - debug:
#       var: conf_nginx

# - hosts: manager
#   remote_user: vagrant
#   become: yes
#   become_method: sudo
#   gather_facts: no

#   tasks:
#   - name: Create local registry
#     command: docker run -d -p 5000:5000 --restart=always --name registry registry:2

#   - name: Tag and push to local registry
#     docker_image:
#       # Select nginx_moo image
#       name: nginx_moo
#       # Will be pushed to manager_ip:5000/nginx_moo
#       repository: 192.168.56.2:5000/nginx_moo
#       push: yes
#       source: local

# - hosts: workers
#   remote_user: vagrant
#   become: yes
#   become_method: sudo
#   gather_facts: no

#   tasks:
#   - name: pull an image
#     docker_image:
#       name: 192.168.56.2:5000/nginx_moo
#       source: pull

- hosts: manager
  remote_user: vagrant
  become: yes
  become_method: sudo
  gather_facts: no
  
  tasks:
  - name: Rolling update
    docker_swarm_service:
      name: nginx_sample_webserver
      image: 192.168.56.2:5000/nginx_moo
      update_config:
        parallelism: 1
        delay: 10s
        order: stop-first
      publish:
        published_port: 80
        target_port: 80